### ISSUE TITLE
L_infinite implementation problem

### ISSUE THREAD

**Issue by badchild0912** [carlini/nn_robust_attacks#17]
I try to put the L_infinite attack into cleverhans, but here is some problem I don't understand.
The adversarial image I get always have some nan value. When I look into the code, I find:
In L_infinite implementation, there is a function doit, in which it tries to convert the original image to the tanh-space. 

```
def doit(oimgs, labs, starts, tt, CONST):
# convert to tanh-space
imgs = np.arctanh(np.array(oimgs)*1.999999)
starts = np.arctanh(np.array(starts)*1.999999)

```

Here I don't understand why it times 1.999999 instead of 0.999999.
Because the range of the original images is [0,1], then it changes into [0, 1.999999]. For the part [1,1.999999], the np.arctanh() value becomes inf or nan.  

By the way, I read the original paper for the L2, L0, L infinite attacks, in the paper, the L infinite results are remarkable, but I run the code in this repository, I find the maximum value of the adversarial image is 0.5, the minimum value is -0.5. It is weird, is it the issue of parameters or something goes wrong?

**Comment by gehuangyi20** [comment]
tanh-space has range (-1,1). Image space has range (-0.5, 0.5) See
https://github.com/carlini/nn_robust_attacks/blob/d2067d5a929c86c6ff5a368f5489c7cbd1e73a8c/setup_mnist.py#L26

 That implies times  1.999999

**Comment by badchild0912** [comment]
Ah! Yes, it is true. I never found it before you told me.

**Comment by badchild0912** [comment]
Ah! Yes, it is true. I never found it before you told me. @gehuangyi20

**Comment by badchild0912** [comment]
Thank you very much! @gehuangyi20
