### ISSUE TITLE
why I only change the weight of the attacked model, the examples are not adversarial any more.

### ISSUE THREAD

**Issue by xieyi318** [carlini/nn_robust_attacks#26]
Hi, when I trained the default model for the first time and based on these weights I can generate adversarial examples with 100% attack success rate. But I trained the same model one more time and save the weights, try to attack this second model by the examples I generated based on the first one, it dose not work, the test accuracy is over 65%. Dose it make sense? I thought the adversarial examples should have transferability within the same model but different weights. 
Thank you for your time!!

**Comment by carlini** [comment]
It does have transferability -- it worked 45% of the time here. See Figure 9 of the paper for some comparison of confidence vs. transferability.

**Comment by xieyi318** [comment]
So when I try to explore the defense method, setting higher confidence such as 1 is the best choice?

**Comment by carlini** [comment]
Yes. See also other papers on improving transferability, e.g., https://arxiv.org/abs/1611.02770.
