### ISSUE TITLE
Any adversarial attack that sustains after resize attack

### ISSUE THREAD

**Issue by BalaMallikarjuna-G** [carlini/nn_robust_attacks#38]
Hi Sir,

This is Bala. I have a query regarding adversarial attack.

Is there any adversarial attack that sustains/consists of added noise, after resize attack ? (adversarial image -> converting into High / low resolution image -> resize to original adverarial image size)

Thanks,
Bala

**Comment by carlini** [comment]
If you use some form of EOT (Athalye et al. 2018) then it should be possible to make resize-robust adversarial examples.
