### ISSUE TITLE
Contribute implementation to Foolbox

### ISSUE THREAD

**Issue by wielandbrendel** [carlini/nn_robust_attacks#4]
I am one of the authors of [Foolbox](https://github.com/bethgelab/foolbox), a recently released Python package that aims to provide reference implementations of many adversarial attacks with a uniform API for many different deep learning frameworks. So far we implemented 15+ attacks and provide consistent interfaces to PyTorch, Theano, Tensorflow, Keras, Lasagne and MXNet. The paper on Foolbox is

https://arxiv.org/abs/1707.04131

I'd hereby like to invite you to contribute an implementation of your method. The backend of Foolbox likely needs a couple of small modifications to support your attack but I'd be very happy to assist you. Please let me know if you are interested.

**Comment by carlini** [comment]
I'm currently working on getting my attack implemented with CleverHans (https://github.com/tensorflow/cleverhans). I'm currently pretty strapped for time, so I don't know if I'll be able to get it merged any time soon. (Right now, it's heavily tensorflow-specific.) However if you'd like, my code is BSD, feel free to work with it to add it to Foolbox.

Or: In a month I'll have more time available, and might be able to take a look at adding it there. But I don't know if you want to wait that long.
