### ISSUE TITLE
I want to attack my own model training by tensorflow2.0.

### ISSUE THREAD

**Issue by Madanfeng** [carlini/nn_robust_attacks#40]
I want to attack my own model training by tensorflow2.0, how do I modify the code?

**Comment by carlini** [comment]
You can probably get almost all of this to work by importing `tf.compat.v1` if you want to use this implementation.

Alternatively, you can use another implementation of this attack built for TF2 from CleverHans, FoolBox, or ART.

**Comment by Madanfeng** [comment]
> You can probably get almost all of this to work by importing `tf.compat.v1` if you want to use this implementation.
> 
> Alternatively, you can use another implementation of this attack built for TF2 from CleverHans, FoolBox, or ART.

Thank your reply, I refer to your code rewriting to tf2, the code is being refined. https://github.com/Madanfeng/CW_TF2
