### ISSUE TITLE
What version of tensorflow + keras?

### ISSUE THREAD

**Issue by kevjunlee** [carlini/nn_robust_attacks#46]
Trying to follow along your attack, I get issues with new TF versions. I'll get errors for nb_epoch (new TF uses just epoch).

However, whenever I set my tf version 1.15 (last version of 1.x) and I try to run python3 train_models.py I get the error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "train_models.py", line 10, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install `tensorflow``

Which versions of tf and keras were used for this project?

Thanks and best

**Comment by naman** [comment]
@kevjunlee did you figure out which version of the libraries were used?
