### ISSUE TITLE
Why the label of attack images is same with the original images?

### ISSUE THREAD

**Issue by shenqixiaojiang** [carlini/nn_robust_attacks#7]
The label of attack images is same with the original images when I use the run_inference_on_image function of setup_inception file. 
So does it mean that the attack almost failed?

**Comment by carlini** [comment]
Sorry I don't quite understand what you're asking. If the prediction is the same for both before and after attack, then the attack has failed. Sometimes this might be because confidence=0 has minor issues, and if you run it with confidence=[some small value] it will often work.

**Comment by shenqixiaojiang** [comment]
@carlini Thanks，I will try the attack with confidence > 0.
